version: '3.4'

services:
  nginx:
    restart: always
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "8080:443"
  db:
    image: mongo
    restart: "always"
    ports:
      - 27017:27017
    environment:
      MONGO_DATABASE: finif
  server:
    image: server
    build:
      context: ./server
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
  client:
    image: client
    build:
      context: ./client
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production